apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: airflow
type: Opaque
stringData: 
  webserver-secret-key: 572379789fbfebbc40285eaa2e20cc4e

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet_key: _c-ks8wgSxYKzrkf8K86BblPvi2yls-g8xIu7qqdLOk=